# Generated by Django 2.0.4 on 2018-05-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldtravelapp', '0004_auto_20180503_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(default='Россия Санкт-Петербург Экскурсионный', max_length=100, verbose_name='Тэги'),
            preserve_default=False,
        ),
    ]
