# Generated by Django 2.0.4 on 2018-05-05 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worldtravelapp', '0005_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='photo_prev',
        ),
    ]
