# Generated by Django 2.0.4 on 2018-05-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldtravelapp', '0006_remove_post_photo_prev'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, default='', upload_to='news_images/', verbose_name='Фото к статье'),
        ),
    ]
