# Generated by Django 2.0.4 on 2018-05-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldtravelapp', '0009_auto_20180507_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(upload_to='users', verbose_name='Фото профиля'),
        ),
    ]
