# Generated by Django 2.0.4 on 2018-05-09 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('worldtravelapp', '0017_auto_20180509_0254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('email', models.EmailField(max_length=40, verbose_name='E-mail')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='NearestDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата тура')),
            ],
            options={
                'verbose_name': 'Дата тура',
                'verbose_name_plural': 'Даты туров',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Отзыв')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('approved_reviews', models.BooleanField(default=False, verbose_name='Одобренный отзыв')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_tour', models.CharField(choices=[('EXC', 'Экскурсионный'), ('BEA', 'Пляжный'), ('WEE', 'Выходного дня'), ('ACT', 'Активный')], default='EXC', max_length=3, verbose_name='Тип тура')),
                ('duration', models.IntegerField(verbose_name='Продолжительность')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('cities', models.CharField(max_length=200, verbose_name='Города')),
                ('countries', models.CharField(max_length=200, verbose_name='Страны')),
                ('title', models.CharField(max_length=200, verbose_name='Название тура')),
                ('text', models.TextField(verbose_name='Описание тура')),
                ('photo', models.ImageField(blank=True, default='', upload_to='tours/', verbose_name='Фото тура')),
                ('nearest_date', models.ManyToManyField(related_name='tours', to='worldtravelapp.NearestDate', verbose_name='Ближайшие даты')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('job', models.CharField(max_length=40, verbose_name='Должность')),
                ('photo', models.ImageField(blank=True, default='', upload_to='news_images/', verbose_name='Фото сотрудника')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='worldtravelapp.Tour', verbose_name='Тур'),
        ),
        migrations.AddField(
            model_name='nearestdate',
            name='tours_list',
            field=models.ManyToManyField(related_name='dates', to='worldtravelapp.Tour', verbose_name='Туры'),
        ),
    ]
