# Generated by Django 2.0.4 on 2018-05-09 13:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('worldtravelapp', '0018_auto_20180509_1610'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tour',
            options={'ordering': ['title'], 'verbose_name': 'Тур', 'verbose_name_plural': 'Туры'},
        ),
        migrations.AlterField(
            model_name='nearestdate',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Дата тура'),
        ),
    ]
