# Generated by Django 2.0.4 on 2018-05-09 13:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('worldtravelapp', '0019_auto_20180509_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nearestdate',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата тура'),
        ),
        migrations.AlterField(
            model_name='nearestdate',
            name='tours_list',
            field=models.ManyToManyField(blank=True, related_name='dates', to='worldtravelapp.Tour', verbose_name='Туры'),
        ),
    ]
