# Generated by Django 2.0.4 on 2018-05-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldtravelapp', '0020_auto_20180509_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nearestdate',
            name='tours_list',
            field=models.ManyToManyField(related_name='dates', to='worldtravelapp.Tour', verbose_name='Туры'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='nearest_date',
            field=models.ManyToManyField(blank=True, related_name='tours', to='worldtravelapp.NearestDate', verbose_name='Ближайшие даты'),
        ),
    ]
