# Generated by Django 2.0.4 on 2018-05-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldtravelapp', '0022_auto_20180509_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок дня')),
                ('number', models.IntegerField(verbose_name='Номер дня')),
                ('text', models.TextField(verbose_name='Описание дня')),
                ('tour', models.ManyToManyField(blank=True, related_name='days', to='worldtravelapp.Tour', verbose_name='Туры')),
            ],
            options={
                'verbose_name': 'День',
                'verbose_name_plural': 'Дни',
            },
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='users/', verbose_name='Фото профиля'),
        ),
    ]
