# Generated by Django 2.0.4 on 2018-05-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldtravelapp', '0023_auto_20180511_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day',
            old_name='tour',
            new_name='tours_list',
        ),
        migrations.AddField(
            model_name='tour',
            name='set_days',
            field=models.ManyToManyField(blank=True, related_name='tours', to='worldtravelapp.Day', verbose_name='Программа тура'),
        ),
    ]
