# Generated by Django 2.0.4 on 2018-05-11 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worldtravelapp', '0024_auto_20180511_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='tours_list',
        ),
        migrations.AddField(
            model_name='day',
            name='tours_list',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='worldtravelapp.Tour', verbose_name='Тур'),
            preserve_default=False,
        ),
    ]
