# Generated by Django 2.0.4 on 2018-05-11 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worldtravelapp', '0025_auto_20180511_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='set_days',
        ),
    ]
