# Generated by Django 2.0.4 on 2018-05-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldtravelapp', '0026_remove_tour_set_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='transport',
            field=models.CharField(choices=[('AUT', 'Атобусный'), ('AVI', 'Авиа'), ('CRU', 'Круизный')], default='AUT', max_length=3, verbose_name='Тип транспорта'),
        ),
    ]
