# Generated by Django 2.0.4 on 2018-05-11 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worldtravelapp', '0027_tour_transport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nearestdate',
            name='tours_list',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='nearest_date',
        ),
        migrations.AddField(
            model_name='nearestdate',
            name='tour',
            field=models.ForeignKey(blank=True, default=2, on_delete=django.db.models.deletion.CASCADE, to='worldtravelapp.Tour', verbose_name='Тур'),
            preserve_default=False,
        ),
    ]
