# Generated by Django 2.0.4 on 2018-05-11 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worldtravelapp', '0028_auto_20180511_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nearestdate',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worldtravelapp.Tour', verbose_name='Тур'),
        ),
    ]
