# Generated by Django 2.0.4 on 2018-05-12 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worldtravelapp', '0029_auto_20180511_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название')),
                ('photo', models.ImageField(blank=True, upload_to='news_images/', verbose_name='Фото города')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название')),
                ('continent', models.CharField(max_length=30, verbose_name='Континент')),
                ('photo', models.ImageField(blank=True, upload_to='news_images/', verbose_name='Фото страны')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.AlterField(
            model_name='day',
            name='tours_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='worldtravelapp.Tour', verbose_name='Тур'),
        ),
        migrations.AlterField(
            model_name='nearestdate',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nearestdates', to='worldtravelapp.Tour', verbose_name='Тур'),
        ),
        migrations.RemoveField(
            model_name='tour',
            name='cities',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='countries',
        ),
        migrations.AlterField(
            model_name='tour',
            name='duration',
            field=models.IntegerField(verbose_name='Количество заказов'),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citys', to='worldtravelapp.Tour', verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='tour',
            name='cities',
            field=models.ManyToManyField(related_name='tours', to='worldtravelapp.City', verbose_name='Города'),
        ),
        migrations.AddField(
            model_name='tour',
            name='countries',
            field=models.ManyToManyField(related_name='tours', to='worldtravelapp.Country', verbose_name='Страны'),
        ),
    ]
