# Generated by Django 2.0.4 on 2018-05-12 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldtravelapp', '0032_hottour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hottour',
            name='text',
            field=models.TextField(max_length=30, verbose_name='Описание'),
        ),
    ]
