# Generated by Django 2.0.4 on 2018-05-12 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldtravelapp', '0033_auto_20180512_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='hottour',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='Скидка'),
            preserve_default=False,
        ),
    ]
