# Generated by Django 2.0.4 on 2018-05-12 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldtravelapp', '0035_auto_20180513_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='duration',
            field=models.IntegerField(verbose_name='Количество дней'),
        ),
    ]
