# Generated by Django 2.0.4 on 2018-05-12 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldtravelapp', '0037_auto_20180513_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hottour',
            name='text',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
