# Generated by Django 2.0.4 on 2018-05-13 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldtravelapp', '0038_auto_20180513_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='order_count',
            field=models.IntegerField(default=0, verbose_name='Количество заказов'),
            preserve_default=False,
        ),
    ]
