# Generated by Django 2.0.4 on 2018-05-13 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worldtravelapp', '0039_tour_order_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='cities',
            new_name='citys',
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='countries',
            new_name='countrys',
        ),
    ]
