# Generated by Django 2.0.4 on 2018-05-13 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldtravelapp', '0040_auto_20180513_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='nearestdate',
            name='count_place',
            field=models.IntegerField(default=40, verbose_name='Количество мест'),
            preserve_default=False,
        ),
    ]
