# Generated by Django 2.0.4 on 2018-05-13 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldtravelapp', '0041_nearestdate_count_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nearestdate',
            name='count_place',
            field=models.IntegerField(blank=True, verbose_name='Количество мест'),
        ),
    ]
