# Generated by Django 2.0.4 on 2018-05-13 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldtravelapp', '0043_auto_20180514_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='continent',
            field=models.CharField(default='', max_length=20, verbose_name='Континент'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tour',
            name='duration',
            field=models.IntegerField(verbose_name='Продолжительность'),
        ),
    ]
