# Generated by Django 2.0.4 on 2018-05-14 09:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('worldtravelapp', '0044_auto_20180514_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nearestdate',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Дата тура'),
        ),
    ]
