# Generated by Django 2.0.4 on 2018-05-14 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldtravelapp', '0045_auto_20180514_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='useful_info',
            field=models.TextField(default='', verbose_name='Полезная информация'),
            preserve_default=False,
        ),
    ]
