# Generated by Django 2.0.4 on 2018-05-15 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldtravelapp', '0046_tour_useful_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='tour_in',
            field=models.TextField(default='', verbose_name='Входит в стоимость'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='tour_out',
            field=models.TextField(default='', verbose_name='Не входит в стоимость'),
            preserve_default=False,
        ),
    ]
