# Generated by Django 2.0.4 on 2018-05-15 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('worldtravelapp', '0048_auto_20180515_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Отзыв')),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время заказа')),
                ('desire_order', models.BooleanField(default=False, verbose_name='Желаемый заказ')),
                ('order', models.BooleanField(default=False, verbose_name='Заказанный')),
                ('success_order', models.BooleanField(default=False, verbose_name='Обаботанный заказ')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Заказчик')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='worldtravelapp.Tour', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
