# Generated by Django 2.0.4 on 2018-05-15 15:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('worldtravelapp', '0049_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='text',
        ),
        migrations.AddField(
            model_name='order',
            name='tour_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Дата тура'),
        ),
    ]
