# Generated by Django 2.0.4 on 2018-05-16 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldtravelapp', '0051_userprofile_tel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='success_order',
            new_name='order_complete',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, max_length=20, verbose_name='Статус'),
        ),
    ]
