# Generated by Django 2.0.4 on 2018-05-16 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldtravelapp', '0052_auto_20180516_1324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nearestdate',
            options={'ordering': ['date'], 'verbose_name': 'Дата тура', 'verbose_name_plural': 'Даты туров'},
        ),
        migrations.AlterField(
            model_name='city',
            name='title',
            field=models.CharField(max_length=30, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='country',
            name='title',
            field=models.CharField(max_length=30, unique=True, verbose_name='Название'),
        ),
        migrations.AlterUniqueTogether(
            name='worker',
            unique_together={('first_name', 'last_name')},
        ),
    ]
