# Generated by Django 2.0.4 on 2018-05-16 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldtravelapp', '0053_auto_20180516_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.FloatField(default=0, verbose_name='Сумма'),
            preserve_default=False,
        ),
    ]
