# Generated by Django 2.0.4 on 2018-05-16 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldtravelapp', '0054_order_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nearestdate',
            name='count_place',
            field=models.IntegerField(blank=True, default=40, null=True, verbose_name='Количество мест'),
        ),
        migrations.AlterUniqueTogether(
            name='nearestdate',
            unique_together={('date', 'tour')},
        ),
    ]
