# Generated by Django 2.0.4 on 2018-05-16 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worldtravelapp', '0057_auto_20180517_0141'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nearestdate',
            unique_together=set(),
        ),
    ]
