# Generated by Django 2.0.4 on 2018-05-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldtravelapp', '0058_auto_20180517_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tour',
            field=models.CharField(blank=True, max_length=20, verbose_name='Статус'),
        ),
    ]
