# Generated by Django 2.0.4 on 2018-05-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldtravelapp', '0061_auto_20180517_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='complete',
            field=models.BooleanField(default=False, verbose_name='Готов'),
        ),
    ]
