# Generated by Django 2.0.4 on 2018-05-17 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldtravelapp', '0063_auto_20180518_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='continent',
            field=models.CharField(choices=[('Африка', 'Африка'), ('Азия', 'Азия'), ('Австралия', 'Австралия'), ('Россия', 'Россия'), ('Европа', 'Европа'), ('Северная Америка', 'Северная Америка'), ('Южная Америка', 'Южная Америка')], default='Россия', max_length=50, verbose_name='Континент'),
        ),
    ]
