# Generated by Django 2.0.4 on 2018-05-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldtravelapp', '0065_hottour_date_tour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nearestdate',
            name='date',
            field=models.CharField(blank=True, max_length=15, verbose_name='Дата тура'),
        ),
    ]
