# Generated by Django 2.0.4 on 2018-05-18 16:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('worldtravelapp', '0066_auto_20180518_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hottour',
            name='date_tour',
            field=models.CharField(blank=True, max_length=30, verbose_name='Дата тура'),
        ),
        migrations.AlterField(
            model_name='nearestdate',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Дата тура'),
        ),
    ]
