# Generated by Django 2.0.4 on 2018-05-18 16:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('worldtravelapp', '0067_auto_20180518_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hottour',
            name='date_tour',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Дата тура'),
        ),
    ]
