# Generated by Django 2.0.4 on 2018-05-18 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worldtravelapp', '0068_auto_20180518_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hottour',
            name='date_tour',
        ),
    ]
