# Generated by Django 2.0.4 on 2018-05-19 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldtravelapp', '0070_hottour_date_tour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='number',
            field=models.IntegerField(unique=True, verbose_name='Номер дня'),
        ),
    ]
