# Generated by Django 2.0.4 on 2018-05-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldtravelapp', '0071_auto_20180519_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='number',
            field=models.IntegerField(verbose_name='Номер дня'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='continent',
            field=models.CharField(choices=[('Африка', 'Африка'), ('Азия', 'Азия'), ('Австралия', 'Австралия'), ('Россия', 'Россия'), ('Европа', 'Европа'), ('Северная Америка', 'Северная Америка'), ('Южная Америка', 'Южная Америка')], default='Россия', max_length=20, verbose_name='Континент'),
        ),
        migrations.AlterUniqueTogether(
            name='day',
            unique_together={('number', 'tours_list')},
        ),
    ]
