# Generated by Django 2.0.4 on 2018-05-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldtravelapp', '0072_auto_20180519_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='number',
            field=models.PositiveSmallIntegerField(verbose_name='Номер дня'),
        ),
        migrations.AlterField(
            model_name='hottour',
            name='discount',
            field=models.PositiveSmallIntegerField(verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='nearestdate',
            name='count_place',
            field=models.PositiveSmallIntegerField(blank=True, default=40, null=True, verbose_name='Количество мест'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.PositiveSmallIntegerField(verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='duration',
            field=models.PositiveSmallIntegerField(verbose_name='Продолжительность'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='order_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Количество заказов'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='price',
            field=models.PositiveSmallIntegerField(verbose_name='Цена'),
        ),
    ]
