# Generated by Django 2.0.4 on 2018-05-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='short_descript',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
